refactor(staging): reorganize environment variable upload step
- moved the upload of environment variables to occur after file copying to VPS for better deployment flow
- ensured the environment variable setup is executed in the correct sequence to avoid potential issues during deployment

This change improves the deployment process by ensuring that environment variables are set up after the necessary files have been copied to the server.

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -18,11 +18,6 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
 
-      - name: Upload Environment Variables
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_VPS_IP }} << 'EOF'
-            echo "${{ secrets.STAGING_FRONTEND_ENV }}" | sudo tee ${{ secrets.PROJECT_PATH }}/.env.production > /dev/null || { echo "Failed to create .env.production file"; exit 1; }
-          EOF
 
       - name: Copy Files to VPS
         run: |
@@ -32,6 +27,12 @@ jobs:
             --exclude='node_modules' \
             --exclude='.next' \
             . ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_VPS_IP }}:${{ secrets.PROJECT_PATH }}
+
+      - name: Upload Environment Variables
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_SSH_USER }}@${{ secrets.STAGING_VPS_IP }} << 'EOF'
+            echo "${{ secrets.STAGING_FRONTEND_ENV }}" | sudo tee ${{ secrets.PROJECT_PATH }}/.env.production > /dev/null || { echo "Failed to create .env.production file"; exit 1; }
+          EOF
 
       - name: Run Deployment Script on VPS
         run: |
